sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/1kg/vcf2vcf/run1kg.vcf2json.chrY.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/1kg/vcf2vcf/run1kg.vcf2json.chrX.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/1kg/vcf2vcf/run1kg.vcf2json.chr13.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/1kg/vcf2vcf/run1kg.vcf2json.chr12.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/1kg/vcf2vcf/run1kg.vcf2json.chr11.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/1kg/vcf2vcf/run1kg.vcf2json.chr10.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/1kg/vcf2vcf/run1kg.vcf2json.chr17.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/1kg/vcf2vcf/run1kg.vcf2json.chr16.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/1kg/vcf2vcf/run1kg.vcf2json.chr15.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/1kg/vcf2vcf/run1kg.vcf2json.chr14.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/1kg/vcf2vcf/run1kg.vcf2json.chr19.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/1kg/vcf2vcf/run1kg.vcf2json.chr18.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/1kg/vcf2vcf/run1kg.vcf2json.chr22.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/1kg/vcf2vcf/run1kg.vcf2json.chr20.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/1kg/vcf2vcf/run1kg.vcf2json.chr21.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/1kg/vcf2vcf/run1kg.vcf2json.chr7.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/1kg/vcf2vcf/run1kg.vcf2json.chr6.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/1kg/vcf2vcf/run1kg.vcf2json.chr5.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/1kg/vcf2vcf/run1kg.vcf2json.chr4.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/1kg/vcf2vcf/run1kg.vcf2json.chr3.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/1kg/vcf2vcf/run1kg.vcf2json.chr2.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/1kg/vcf2vcf/run1kg.vcf2json.chr1.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/1kg/vcf2vcf/run1kg.vcf2json.chr9.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/1kg/vcf2vcf/run1kg.vcf2json.chr8.mapred.sh
