sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/merge/merge/merge.chr1.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/merge/merge/merge.chr10.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/merge/merge/merge.chr11.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/merge/merge/merge.chr12.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/merge/merge/merge.chr13.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/merge/merge/merge.chr14.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/merge/merge/merge.chr15.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/merge/merge/merge.chr16.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/merge/merge/merge.chr17.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/merge/merge/merge.chr18.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/merge/merge/merge.chr19.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/merge/merge/merge.chr2.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/merge/merge/merge.chr20.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/merge/merge/merge.chr21.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/merge/merge/merge.chr22.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/merge/merge/merge.chr3.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/merge/merge/merge.chr4.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/merge/merge/merge.chr5.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/merge/merge/merge.chr6.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/merge/merge/merge.chr7.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/merge/merge/merge.chr8.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/merge/merge/merge.chr9.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/merge/merge/merge.chrGL000191.1.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/merge/merge/merge.chrGL000192.1.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/merge/merge/merge.chrGL000193.1.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/merge/merge/merge.chrGL000194.1.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/merge/merge/merge.chrGL000195.1.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/merge/merge/merge.chrGL000196.1.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/merge/merge/merge.chrGL000197.1.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/merge/merge/merge.chrGL000198.1.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/merge/merge/merge.chrGL000199.1.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/merge/merge/merge.chrGL000201.1.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/merge/merge/merge.chrGL000202.1.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/merge/merge/merge.chrGL000203.1.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/merge/merge/merge.chrGL000204.1.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/merge/merge/merge.chrGL000205.1.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/merge/merge/merge.chrGL000206.1.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/merge/merge/merge.chrGL000207.1.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/merge/merge/merge.chrGL000208.1.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/merge/merge/merge.chrGL000209.1.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/merge/merge/merge.chrGL000210.1.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/merge/merge/merge.chrGL000211.1.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/merge/merge/merge.chrGL000212.1.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/merge/merge/merge.chrGL000213.1.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/merge/merge/merge.chrGL000214.1.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/merge/merge/merge.chrGL000215.1.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/merge/merge/merge.chrGL000216.1.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/merge/merge/merge.chrGL000217.1.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/merge/merge/merge.chrGL000218.1.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/merge/merge/merge.chrGL000219.1.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/merge/merge/merge.chrGL000220.1.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/merge/merge/merge.chrGL000221.1.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/merge/merge/merge.chrGL000222.1.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/merge/merge/merge.chrGL000223.1.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/merge/merge/merge.chrGL000224.1.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/merge/merge/merge.chrGL000225.1.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/merge/merge/merge.chrGL000226.1.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/merge/merge/merge.chrGL000227.1.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/merge/merge/merge.chrGL000228.1.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/merge/merge/merge.chrGL000229.1.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/merge/merge/merge.chrGL000230.1.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/merge/merge/merge.chrGL000231.1.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/merge/merge/merge.chrGL000232.1.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/merge/merge/merge.chrGL000233.1.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/merge/merge/merge.chrGL000234.1.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/merge/merge/merge.chrGL000235.1.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/merge/merge/merge.chrGL000236.1.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/merge/merge/merge.chrGL000237.1.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/merge/merge/merge.chrGL000238.1.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/merge/merge/merge.chrGL000239.1.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/merge/merge/merge.chrGL000240.1.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/merge/merge/merge.chrGL000241.1.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/merge/merge/merge.chrGL000242.1.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/merge/merge/merge.chrGL000243.1.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/merge/merge/merge.chrGL000244.1.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/merge/merge/merge.chrGL000245.1.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/merge/merge/merge.chrGL000246.1.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/merge/merge/merge.chrGL000247.1.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/merge/merge/merge.chrGL000248.1.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/merge/merge/merge.chrGL000249.1.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/merge/merge/merge.chrM.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/merge/merge/merge.chrMT.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/merge/merge/merge.chrNC_007605.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/merge/merge/merge.chrX.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/merge/merge/merge.chrY.mapred.sh
