sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/1kg/unify/run1kg.unify.chrY.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/1kg/unify/run1kg.unify.chrX.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/1kg/unify/run1kg.unify.chr13.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/1kg/unify/run1kg.unify.chr12.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/1kg/unify/run1kg.unify.chr11.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/1kg/unify/run1kg.unify.chr10.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/1kg/unify/run1kg.unify.chr17.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/1kg/unify/run1kg.unify.chr16.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/1kg/unify/run1kg.unify.chr15.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/1kg/unify/run1kg.unify.chr14.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/1kg/unify/run1kg.unify.chr19.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/1kg/unify/run1kg.unify.chr18.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/1kg/unify/run1kg.unify.chr22.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/1kg/unify/run1kg.unify.chr20.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/1kg/unify/run1kg.unify.chr21.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/1kg/unify/run1kg.unify.chr7.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/1kg/unify/run1kg.unify.chr6.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/1kg/unify/run1kg.unify.chr5.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/1kg/unify/run1kg.unify.chr4.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/1kg/unify/run1kg.unify.chr3.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/1kg/unify/run1kg.unify.chr2.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/1kg/unify/run1kg.unify.chr1.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/1kg/unify/run1kg.unify.chr9.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/1kg/unify/run1kg.unify.chr8.mapred.sh
