sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/NIEHS/unify/unify.chr1.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/NIEHS/unify/unify.chr10.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/NIEHS/unify/unify.chr11.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/NIEHS/unify/unify.chr12.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/NIEHS/unify/unify.chr13.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/NIEHS/unify/unify.chr14.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/NIEHS/unify/unify.chr15.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/NIEHS/unify/unify.chr16.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/NIEHS/unify/unify.chr17.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/NIEHS/unify/unify.chr18.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/NIEHS/unify/unify.chr19.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/NIEHS/unify/unify.chr2.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/NIEHS/unify/unify.chr20.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/NIEHS/unify/unify.chr21.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/NIEHS/unify/unify.chr22.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/NIEHS/unify/unify.chr3.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/NIEHS/unify/unify.chr4.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/NIEHS/unify/unify.chr5.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/NIEHS/unify/unify.chr6.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/NIEHS/unify/unify.chr7.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/NIEHS/unify/unify.chr8.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/NIEHS/unify/unify.chr9.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/NIEHS/unify/unify.chrGL000191.1.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/NIEHS/unify/unify.chrGL000192.1.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/NIEHS/unify/unify.chrGL000193.1.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/NIEHS/unify/unify.chrGL000194.1.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/NIEHS/unify/unify.chrGL000195.1.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/NIEHS/unify/unify.chrGL000196.1.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/NIEHS/unify/unify.chrGL000197.1.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/NIEHS/unify/unify.chrGL000198.1.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/NIEHS/unify/unify.chrGL000199.1.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/NIEHS/unify/unify.chrGL000201.1.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/NIEHS/unify/unify.chrGL000202.1.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/NIEHS/unify/unify.chrGL000203.1.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/NIEHS/unify/unify.chrGL000204.1.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/NIEHS/unify/unify.chrGL000205.1.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/NIEHS/unify/unify.chrGL000206.1.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/NIEHS/unify/unify.chrGL000207.1.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/NIEHS/unify/unify.chrGL000208.1.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/NIEHS/unify/unify.chrGL000209.1.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/NIEHS/unify/unify.chrGL000210.1.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/NIEHS/unify/unify.chrGL000211.1.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/NIEHS/unify/unify.chrGL000212.1.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/NIEHS/unify/unify.chrGL000213.1.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/NIEHS/unify/unify.chrGL000214.1.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/NIEHS/unify/unify.chrGL000215.1.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/NIEHS/unify/unify.chrGL000216.1.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/NIEHS/unify/unify.chrGL000217.1.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/NIEHS/unify/unify.chrGL000218.1.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/NIEHS/unify/unify.chrGL000219.1.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/NIEHS/unify/unify.chrGL000220.1.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/NIEHS/unify/unify.chrGL000221.1.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/NIEHS/unify/unify.chrGL000222.1.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/NIEHS/unify/unify.chrGL000223.1.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/NIEHS/unify/unify.chrGL000224.1.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/NIEHS/unify/unify.chrGL000225.1.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/NIEHS/unify/unify.chrGL000226.1.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/NIEHS/unify/unify.chrGL000227.1.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/NIEHS/unify/unify.chrGL000228.1.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/NIEHS/unify/unify.chrGL000229.1.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/NIEHS/unify/unify.chrGL000230.1.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/NIEHS/unify/unify.chrGL000231.1.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/NIEHS/unify/unify.chrGL000232.1.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/NIEHS/unify/unify.chrGL000233.1.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/NIEHS/unify/unify.chrGL000234.1.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/NIEHS/unify/unify.chrGL000235.1.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/NIEHS/unify/unify.chrGL000236.1.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/NIEHS/unify/unify.chrGL000237.1.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/NIEHS/unify/unify.chrGL000238.1.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/NIEHS/unify/unify.chrGL000239.1.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/NIEHS/unify/unify.chrGL000240.1.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/NIEHS/unify/unify.chrGL000241.1.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/NIEHS/unify/unify.chrGL000242.1.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/NIEHS/unify/unify.chrGL000243.1.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/NIEHS/unify/unify.chrGL000244.1.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/NIEHS/unify/unify.chrGL000245.1.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/NIEHS/unify/unify.chrGL000246.1.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/NIEHS/unify/unify.chrGL000247.1.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/NIEHS/unify/unify.chrGL000248.1.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/NIEHS/unify/unify.chrGL000249.1.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/NIEHS/unify/unify.chrMT.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/NIEHS/unify/unify.chrNC_007605.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/NIEHS/unify/unify.chrX.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/NIEHS/unify/unify.chrY.mapred.sh
