sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/BGI1kg/SplitChr/SplitChar.chrY.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/BGI1kg/SplitChr/SplitChar.chrX.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/BGI1kg/SplitChr/SplitChar.chr13.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/BGI1kg/SplitChr/SplitChar.chr12.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/BGI1kg/SplitChr/SplitChar.chr11.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/BGI1kg/SplitChr/SplitChar.chr10.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/BGI1kg/SplitChr/SplitChar.chr17.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/BGI1kg/SplitChr/SplitChar.chr16.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/BGI1kg/SplitChr/SplitChar.chr15.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/BGI1kg/SplitChr/SplitChar.chr14.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/BGI1kg/SplitChr/SplitChar.chr19.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/BGI1kg/SplitChr/SplitChar.chr18.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/BGI1kg/SplitChr/SplitChar.chr22.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/BGI1kg/SplitChr/SplitChar.chr20.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/BGI1kg/SplitChr/SplitChar.chr21.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/BGI1kg/SplitChr/SplitChar.chr7.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/BGI1kg/SplitChr/SplitChar.chr6.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/BGI1kg/SplitChr/SplitChar.chr5.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/BGI1kg/SplitChr/SplitChar.chr4.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/BGI1kg/SplitChr/SplitChar.chr3.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/BGI1kg/SplitChr/SplitChar.chr2.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/BGI1kg/SplitChr/SplitChar.chr1.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/BGI1kg/SplitChr/SplitChar.chr9.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/BGI1kg/SplitChr/SplitChar.chr8.mapred.sh
