sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/BGI-Psorasis/unify/unify.chr1.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/BGI-Psorasis/unify/unify.chr10.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/BGI-Psorasis/unify/unify.chr11.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/BGI-Psorasis/unify/unify.chr12.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/BGI-Psorasis/unify/unify.chr13.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/BGI-Psorasis/unify/unify.chr14.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/BGI-Psorasis/unify/unify.chr15.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/BGI-Psorasis/unify/unify.chr16.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/BGI-Psorasis/unify/unify.chr17.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/BGI-Psorasis/unify/unify.chr18.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/BGI-Psorasis/unify/unify.chr19.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/BGI-Psorasis/unify/unify.chr2.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/BGI-Psorasis/unify/unify.chr20.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/BGI-Psorasis/unify/unify.chr21.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/BGI-Psorasis/unify/unify.chr22.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/BGI-Psorasis/unify/unify.chr3.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/BGI-Psorasis/unify/unify.chr4.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/BGI-Psorasis/unify/unify.chr5.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/BGI-Psorasis/unify/unify.chr6.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/BGI-Psorasis/unify/unify.chr7.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/BGI-Psorasis/unify/unify.chr8.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/BGI-Psorasis/unify/unify.chr9.mapred.sh
sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/BGI-Psorasis/unify/unify.chrX.mapred.sh
#sh /ifs4/ISDC_BD/xiaopeng2/src/DHGV/script/BGI-Psorasis/unify/unify.chrY.mapred.sh
